name: Test Project Workflow # The name of the workflow

on: push # The workflow is triggered on push events

jobs: # Defines a collection of jobs to be run as part of the workflow
    test:  # A job named "test"
        runs-on: ubuntu-latest # Specifies the type of machine to run the job on
        steps: # A series of steps to be executed as part of the job
            - name: Get Code # A step named "Get Code"
              uses: actions/checkout@v6 # Uses the checkout action to clone the repository
            #   with: # Use with for adding Parameters for the checkout action ref: https://github.com/marketplace/actions/checkout
            - uses: actions/setup-node@v6
              with:
                node-version: 24
            - name: Install Dependencies # A step named "Install Dependencies"
            #   run: npm install # Runs the command to install project dependencies
              run: npm ci # Uses npm ci for clean install based on package-lock.json
            - name: Run Tests # A step named "Run Tests"
              run: npm test # Runs the command to execute the tests
    deploy: # A job named "deploy"
      runs-on: ubuntu-latest # Specifies the type of machine to run the job on
      # needs: test # This job depends on the successful completion of the "test" job
      steps: # A series of steps to be executed as part of the job
          - name: Get Code # A step named "Get Code"
            uses: actions/checkout@v6 # Uses the checkout action to clone the repository
          #   with: # Use with for adding Parameters for the checkout action ref: https://github.com/marketplace/actions/checkout
          - uses: actions/setup-node@v6
            with:
              node-version: 24
          - name: Install Dependencies # A step named "Install Dependencies"
            run: npm ci # Uses npm ci for clean install based on package-lock.json
          - name: Build Application # A step named "Build Application"
            run: npm run build # Runs the command to build the application
          - name: Deploy Application # A step named "Deploy Application"
            run: echo "Deploying application." # A placeholder command for deployment
